Traceback (most recent call last):
  File "main_supcon.py", line 349, in <module>
    main()
  File "main_supcon.py", line 329, in main
    loss = train()
  File "main_supcon.py", line 261, in train
    features = model(images)
  File "C:\Users\aryan\.conda\envs\newenv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Cornell Tech\MLH\PD-Prediction\networks\resnet_big.py", line 184, in forward
    feat = self.encoder(x)
  File "C:\Users\aryan\.conda\envs\newenv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Cornell Tech\MLH\PD-Prediction\networks\resnet_big.py", line 118, in forward
    out = self.layer1(out)
  File "C:\Users\aryan\.conda\envs\newenv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\aryan\.conda\envs\newenv\lib\site-packages\torch\nn\modules\container.py", line 204, in forward
    input = module(input)
  File "C:\Users\aryan\.conda\envs\newenv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Cornell Tech\MLH\PD-Prediction\networks\resnet_big.py", line 63, in forward
    out = F.relu(self.bn1(self.conv1(x)))
  File "C:\Users\aryan\.conda\envs\newenv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\aryan\.conda\envs\newenv\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\aryan\.conda\envs\newenv\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: [enforce fail at C:\cb\pytorch_1000000000000\work\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 134217728 bytes.